name: Deploy to DigitalOcean

on:
  push:
    branches:
      - ft-packages

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - run: npm install
      - run: npm run build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: digitalocean/actions/deploy@v2
        with:
          access-token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          droplet-id: ${{ secrets.DIGITALOCEAN_DROPLET_ID }}
          app-name: my-app
          path: dist